config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]

build:
  correctness:
    test-sample-bootstrapper:
      filter:
        owner: vaticle
        branch: development
      image: vaticle-ubuntu-21.04
      type: foreground
      command: |
        sudo apt-get update -y
        sudo apt-get install -y docker
        sudo service docker start
        docker build  . -f typedb-samples-docker/Dockerfile  --tag test-typedb-samples
        docker run -p 1729:1729   -e BOOTSTRAPPER_VERBOSE=true -e BOOTSTRAPPER_CONFIG=/typedb-samples/__test/config.yml -e BOOTSTRAPPER_DATASET_ROOT=/typedb-samples/__test --name test-typedb-samples-container test-typedb-samples &
        sleep 30
        docker exec test-typedb-samples-container typedb console --command="database list"  && export TEST_SUCCESS=0 || export TEST_SUCCESS=1 
        docker stop test-typedb-samples-container; docker rm test-typedb-samples-container
        exit $TEST_SUCCESS
    deploy-development:
      filter:
        owner: vaticle
        branch: development
      image: vaticle-ubuntu-21.04
      type: foreground
      command: |
        export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME
        export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL
        export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @vaticle_dependencies//tool/release:docs -- $FACTORY_OWNER typedb-web-docs development $FACTORY_REPO content $FACTORY_COMMIT
    deploy-production:
      filter:
        owner: vaticle
        branch: master
      image: vaticle-ubuntu-21.04
      type: foreground
      command: |
        export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME
        export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL
        export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @vaticle_dependencies//tool/release:docs -- $FACTORY_OWNER typedb-web-docs master $FACTORY_REPO content $FACTORY_COMMIT
  execution:
    - deploy-development
    - deploy-production
